name: Build and deploy ASP.Net Core app to Azure Web App - nfsesp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build with dotnet
        run: dotnet build nfsesp/nfsesp.sln --configuration Release

      - name: dotnet publish
        run: dotnet publish nfsesp/nfsesp.sln -c Release -o ./publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B46B9B0CEEEF4F0DB02AE7ECDC573E8B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C05B429460F14E818B4CEAFDFE3A7BC9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AB8C38BEF1FE4094A12AE335BBE77594 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'nfsesp'
          slot-name: 'Production'
          package: ./publish
